controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
create_time_log:
    path: /create
    controller: App\Controller\TimeLogController::createTimeLog

create_view_log:
    path: /view
    controller: App\Controller\TimeLogController::viewTimeLogs
